name = "heisenberg"
version = "1.0.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
lustre = ">= 5.1.1 and < 6.0.0"
mist = ">= 5.0.3 and < 6.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
repeatedly = ">= 2.1.2 and < 3.0.0"

[dev-dependencies]
radiate = ">= 1.0.0 and < 2.0.0"
