name = "heisenberg"
version = "1.0.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
lustre = ">= 5.1.1 and < 6.0.0"
mist = ">= 4.0.7 and < 5.0.0"
